services:
  pricing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: print-pricing
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=1
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  tmpdata:
  node_modules:
